In [1]:
import pandas as pd

In [2]:
states_data = []

In [3]:
# ACRE

total_masc = 2292
masc_j = [0.2, 0.7, 2.3]
masc_ad = [17.1, 33.2, 23.7, 11.4]
masc_i = [6.9, 3.2, 1.4]

# passando de 100%, lol
(total_masc * (sum(masc_j) + sum(masc_ad) + sum(masc_i))) / 100

print('Casos masculino')
for group in [masc_j, masc_ad, masc_i]:
    print((total_masc * sum(group)/100))

total_fem = 2209
fem_j = [0.3, 0.7, 4.1]
fem_ad = [19.5, 29.5, 23.6, 12.3]
fem_i = [5.7, 2.7, 1.6]   
    
print('Casos fem')
for group in [fem_j, fem_ad, fem_i]:
    print((total_fem * sum(group)/100))
    
# https://agencia.ac.gov.br/wp-content/uploads/2020/05/BOLETIM_COVID-19_ACRE_25_05_2020.pdf

Casos masculino
73.344
1957.3680000000002
263.58000000000004
Casos fem
112.65899999999999
1875.4409999999998
220.9

In [4]:
ac_data = {'state': 'AC', 
           'deaths_young': 1,
           'deaths_adult': 31,
           'deaths_elder': 65,
           'deaths_total': 97,
           'cases_young': 185,
           'cases_adult': 3832, 
           'cases_elder': 483, 
           'cases_total': 4500}
states_data.append(ac_data)

In [5]:
# ALAGOAS
# http://www.saude.al.gov.br/wp-content/uploads/2020/05/Informe-Epidemiol%C3%B3gico-COVID-19-n%C2%BA-82-27-05-2020.pdf

casos_jovem = 94 + 180 + 8 + 3
casos_adulto = 1020 + 1872 + 1602 + 1019 + 32 + 106 + 160 + 166
casos_idoso = 504 + 329 + 209 + 276
total_casos = casos_jovem + casos_adulto + casos_idoso
print(total_casos)

mortes_jovem = 1 + 1 + 2
mortes_adulto = 5 + 2 + 7 + 15 + 13 + 24 + 23 + 27
mortes_idoso = 38 + 48 + 41 + 42 + 34 + 45
total_mortes = mortes_jovem + mortes_adulto + mortes_idoso
print(total_mortes)
al_data = {'state': 'BA', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes, 
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(al_data)

7580
368

In [6]:
# Estados que não possuem dado de faixa etária:
# Amazonas, Amapá, Mato Grosso do Sul (falta óbitos), Mato Grosso (falta óbitos), Paraíba (falta casos), Paraná
# Rio Grande do Norte (não consigo ver os numeros no pdf), Roraima (falta óbitos), Sâo Paulo

In [7]:
# BAHIA
# http://www.saude.ba.gov.br/wp-content/uploads/2020/05/BOLETIM_ELETRONICO_BAHIAN_64___27052020.pdf

casos_jovem = 56 + 89 + 81 + 279
casos_adulto = 1392 + 3082 + 2301 + 1322
casos_idoso = 728+ 417 + 363
ignorados = 4960
total_casos = casos_jovem + casos_adulto + casos_idoso + ignorados

mortes_jovem = 3 + 2 + 0 + 1
mortes_adulto = 8 + 27 + 52 + 87
mortes_idoso = 123 + 108 + 120
total_mortes = mortes_jovem + mortes_adulto + mortes_idoso


ba_data = {'state': 'BA', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes,
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(ba_data)

In [8]:
# CEARÁ

# https://indicadores.integrasus.saude.ce.gov.br/indicadores/indicadores-coronavirus/coronavirus-ceara
casos_jovem = 239 + 265 + 96 + 128 + 154 + 139 + 342 + 275
casos_adulto = 1056 + 797 + 1728 + 1298 + 2166 + 1708 + 2261 + 1857 + 1956 + 1627 + 1722 + 1492 + 1551 + 1420 + 1305 + 1320
casos_idoso = 1087 + 1210 + 939 + 1006 + 841 + 901 + 638 + 646 + 1201 + 1074
ignorados = 1003
total_casos = casos_jovem + casos_adulto + casos_idoso + ignorados

mortes_jovem = 4 + 6 + 1 + 1 + 2 + 1 + 2
mortes_adulto = 8 + 4 + 10 + 12 + 8 + 20 + 14 + 34 + 34 + 51 + 26 + 58 + 43 + 93 + 75 + 111
mortes_idoso = 94 + 138 + 97 + 137 + 133 + 196 + 129 + 170 + 375 + 388
ignorados = 211
total_mortes = mortes_jovem + mortes_adulto + mortes_idoso + ignorados

ce_data = {'state': 'CE', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes,
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(ce_data)

In [9]:
# DISTRITO FEDERAL

# http://www.saude.df.gov.br/wp-conteudo/uploads/2020/03/Boletim-COVID_DF-27_05_-2020.pdf

casos_jovem = 38 + 98 + 232
casos_adulto = 1200 + 1963 + 1593 + 951
casos_idoso = 535 + 217 + 152
total_casos = casos_jovem + casos_adulto + casos_idoso

mortes_jovem = 0
mortes_adulto = 2 + 6 + 8 + 12
mortes_idoso = 28 + 25 + 42
total_mortes = mortes_jovem + mortes_adulto + mortes_idoso
 
df_data = {'state': 'DF', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes,
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(df_data)

In [10]:
# ESPIRITO SANTO
# https://coronavirus.es.gov.br/painel-covid-19-es

casos_jovem = 96 + 63 + 271
casos_adulto = 1677 + 3139 + 2585 + 1777
casos_idoso = 997 + 533 + 279 + 67
total_casos = casos_jovem + casos_adulto + casos_idoso

mortes_jovem = 1
mortes_adulto = 8 + 17 + 41 + 72
mortes_idoso = 115 + 128 + 100 + 29
total_mortes = mortes_jovem + mortes_adulto + mortes_idoso

es_data = {'state': 'ES', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes,
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(es_data)

In [11]:
# GOIÁS
# https://extranet.saude.go.gov.br/pentaho/api/repos/:coronavirus:paineis:painel.wcdf/generatedContent

casos_jovem = 66 + 38 + 62
casos_idoso = 265 + 148 + 83
casos_adulto = 481 + 784 + 707 + 467
total_casos = casos_jovem + casos_adulto + casos_idoso

mortes_jovem = 0
mortes_adulto = 2 + 6 + 6 + 18
mortes_idoso = 26 + 36 + 21
total_mortes = mortes_jovem + mortes_adulto + mortes_idoso

go_data = {'state': 'GO', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes,
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(go_data)

In [12]:
# MARANHÃO

casos_jovem = 281 + 718
casos_adulto = 3419 + 5993 + 4747 + 3277
casos_idoso = 2551 + 2457
ignorados = 4536
total_casos = casos_jovem + casos_adulto + casos_idoso + ignorados

mortes_jovem = 5 + 6
mortes_adulto = 9 + 33 + 60 + 108
mortes_idoso = 239 + 427
total_mortes = mortes_jovem + mortes_adulto + mortes_idoso

ma_data = {'state': 'MA', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes,
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(ma_data)

In [13]:
# MINAS GERAIS
# https://www.saude.mg.gov.br/images/noticias_e_eventos/000_2020/Boletins_Corona/Boletim_Epidemiologico_COVID-19_27.05.2020.pdf

mortes_jovem = 1
mortes_adulto = 5 + 6 + 18 + 28
mortes_idoso = 182
total_mortes = mortes_jovem + mortes_adulto + mortes_idoso

casos_jovem = 34 + 116 + 400 + mortes_jovem
casos_adulto = 1122 + 1957 + 1657 + 1212 + mortes_adulto
casos_idoso = 1261 + mortes_idoso
ignorados = 12
total_casos = casos_jovem + casos_adulto + casos_idoso + ignorados 

mg_data = {'state': 'MG', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes,
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(mg_data)

In [14]:
# PARÁ
# https://www.covid-19.pa.gov.br/#/

casos_jovem = 261 + 272 + 451 + 391
casos_adulto = 2381 + 1888 + 4162 + 4000 + 3615 + 3812 + 2352 + 2759
casos_idoso = 1495 + 1919 + 962 + 1274 + 594 + 743
ignorados = 152 + 216
total_casos = casos_jovem + casos_adulto + casos_idoso + ignorados

mortes_jovem = 5 + 13 + 5 + 5
mortes_adulto = 16 + 19 + 36 + 67 + 60 + 161 + 119 + 280
mortes_idoso = 223 + 429 + 246 + 448 + 236 + 347
total_mortes = mortes_jovem + mortes_adulto + mortes_idoso


pa_data = {'state': 'PA', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes,
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(pa_data)

In [15]:
# PERNAMBUCO
# https://12ad4c92-89c7-4218-9e11-0ee136fa4b92.filesusr.com/ugd/3293a8_5d6b8387404c43b9a2b8cd075a7b39ed.pdf

casos_jovem = 187 + 107 + 642 + 227
casos_adulto = 979 + 2180 + 2432 + 2273 + 2436 + 5019 + 4365 + 2563
casos_idoso = 1912 + 1693 + 1323 + 903 + 404 + 274
total_casos = casos_jovem + casos_adulto + casos_idoso

mortes_jovem = 11 + 8 
mortes_adulto = 30 + 83 + 192 + 354
mortes_idoso = 588 + 603 + 599
total_mortes = mortes_jovem + mortes_adulto + mortes_idoso


pe_data = {'state': 'PE', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes,
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(pe_data)

In [16]:
# Piauí
# https://datastudio.google.com/u/0/reporting/a6dc07e9-4161-4b5a-9f2a-6f9be486e8f9/page/2itOB
total_casos =  4243 
casos_jovem = (sum([3.11, 3.94]) / 100) * total_casos
casos_adulto = (sum([17.49, 26.54, 17.42, 13.65])  / 100) * total_casos
casos_idoso = (sum([8.89, 5.8, 3.18])  / 100) * total_casos
print(casos_jovem + casos_adulto+casos_idoso)


total_mortes = 138
mortes_jovem = (sum([1.45]) / 100) * total_mortes
mortes_adulto = (sum([2.17, 3.62, 8.7, 12.32])  / 100) * total_mortes
mortes_idoso = (sum([23.19, 25.36, 23.19])  / 100) * total_mortes
print(mortes_jovem + mortes_adulto+mortes_idoso)

pi_data = {'state': 'PI', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes,
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(pi_data)

4243.8486
137.99999999999997

In [17]:
# Rio de Janeiro
# http://painel.saude.rj.gov.br/monitoramento/covid19.html

def compute_rj_data():
    return (pd.read_csv('../data/BICOVIDREAIS_26maio.csv')
              .query("classificacao == 'CONFIRMADO'")
              .pipe(lambda df: {
                  'state': 'RJ',
                  'deaths_young': len(df.query("(evolucao == 'OBITO') and (idade < 20)")),
                  'deaths_adult': len(df.query("(evolucao == 'OBITO') and (20 <= idade < 60)")),
                  'deaths_elder': len(df.query("(evolucao == 'OBITO') and (idade >= 60)")),
                  'deaths_total': len(df.query("evolucao == 'OBITO'")),
                  'cases_young': len(df.query("(idade < 20)")), 
                  'cases_adult': len(df.query("(20 <= idade < 60)")),                           
                  'cases_elder': len(df.query("(idade >= 60)")),
                  'cases_total': len(df)   
                  })
           )
rj_data = compute_rj_data()
states_data.append(rj_data)

In [18]:
# Rondônia
# http://covid19.sesau.ro.gov.br/Home/Estatistica

casos_jovem = 219
casos_adulto = 616 + 1154 + 888 + 540
casos_idoso = 264 + 118 + 48 + 15
total_casos = casos_jovem + casos_adulto + casos_idoso


mortes_jovem = 1
mortes_adulto = 1 + 9 + 18 + 23
mortes_idoso = 34 + 31 + 13 + 7
total_mortes = mortes_jovem + mortes_adulto + mortes_idoso

ro_data = {'state': 'RO', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes,
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(ro_data)

In [19]:
# Rio Grande do Sul
# http://ti.saude.rs.gov.br/covid19/
casos_jovem = 30 + 42 + 42 + 59 + 163
casos_adulto = 1364 + 1672 + 1418 + 1041
casos_idoso = 596 + 361 + 260
total_casos = casos_jovem + casos_adulto + casos_idoso

mortes_jovem = 1
mortes_adulto = 3 + 6 + 5 + 19
mortes_idoso = 42 + 59 + 74
total_mortes = mortes_jovem + mortes_adulto + mortes_idoso

rs_data = {'state': 'RS', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes,
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(rs_data)

In [20]:
# Santa Catarina
# http://www.coronavirus.sc.gov.br/wp-content/uploads/2020/05/boletim-epidemiologico-27-05-2020.pdf

casos_jovem = 199 + 288
casos_adulto = 1373 + 1940 + 1487 + 1091
casos_idoso = 596 + 258 + 108 + 22
ignorados = 10
total_casos = casos_jovem + casos_adulto + casos_idoso + ignorados

mortes_jovem = 1
mortes_adulto = 7 + 12 + 16
mortes_idoso = 27 + 32 + 26 + 5
total_mortes = mortes_jovem + mortes_adulto + mortes_idoso

sc_data = {'state': 'SC', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes,
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(sc_data)

In [21]:
# Sergipe 
# https://todoscontraocorona.net.br/wp-content/uploads/2020/05/Boletim-27.05.2020-1.pdf
casos_jovem = 18 + 73 + 146 + 147
casos_adulto = 2854 + 1273 + 794 
casos_idoso = 351 + 159 + 96
total_casos = casos_jovem + casos_adulto + casos_idoso

mortes_jovem = 5 + 2 + 1
mortes_adulto = 15 + 7 + 18
mortes_idoso = 30 + 22 + 26
total_mortes =  mortes_jovem + mortes_adulto + mortes_idoso

se_data = {'state': 'SE', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes,
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(se_data)

In [22]:
# Tocantins
# http://integra.saude.to.gov.br/covid19

casos_jovem = 90 + 217
casos_adulto = 736 + 876 + 655 + 370 
casos_idoso = 190 + 95 + 48
total_casos = casos_jovem + casos_adulto + casos_idoso

mortes_jovem = 0
mortes_adulto = 1 + 4 + 11 + 10
mortes_idoso = 15 + 12 + 15
total_mortes = mortes_adulto + mortes_idoso

to_data = {'state': 'TO', 
           'deaths_young': mortes_jovem, 
           'deaths_adult': mortes_adulto, 
           'deaths_elder': mortes_idoso, 
           'deaths_total': total_mortes,
           'cases_young': casos_jovem, 
           'cases_adult': casos_adulto, 
           'cases_elder': casos_idoso, 
           'cases_total': total_casos}
states_data.append(to_data)

In [62]:
def compute_lethality(df):
    return df.assign(**{f"{subject}_lethality": (df[f"deaths_{subject}"]/df[f"cases_{subject}"])
                       for subject in ['total', 'adult', 'elder', 'young']})

In [63]:
state_reports = pd.DataFrame(states_data).pipe(compute_lethality)

In [64]:
state_reports = state_reports.append((state_reports.drop(columns=['state', 'total_lethality', 'adult_lethality', 'elder_lethality'])
              .sum()
              .to_frame()
              .T
              .assign(state='Brasil')
              .pipe(compute_lethality)), ignore_index=True)

In [65]:
state_reports.to_csv('lethality_rates.csv', index=False)

In [67]:
state_reports

,state,deaths_young,deaths_adult,deaths_elder,deaths_total,cases_young,cases_adult,cases_elder,cases_total,total_lethality,adult_lethality,elder_lethality,young_lethality
0,AC,1.000,31.0000,65.0000,97.0,185.0000,3832.000,483.0000,4500.0,0.021556,0.008090,0.134576,0.005405
1,BA,4.000,116.0000,248.0000,368.0,285.0000,5977.000,1318.0000,7580.0,0.048549,0.019408,0.188164,0.014035
2,BA,6.000,174.0000,351.0000,531.0,505.0000,8097.000,1508.0000,15070.0,0.035236,0.021489,0.232759,0.011881
3,CE,17.000,601.0000,1857.0000,2686.0,1638.0000,25264.000,9543.0000,37448.0,0.071726,0.023789,0.194593,0.010379
4,DF,0.000,28.0000,95.0000,123.0,368.0000,5707.000,904.0000,6979.0,0.017624,0.004906,0.105088,0.000000
5,ES,1.000,138.0000,372.0000,511.0,430.0000,9178.000,1876.0000,11484.0,0.044497,0.015036,0.198294,0.002326
6,GO,0.000,32.0000,83.0000,115.0,166.0000,2439.000,496.0000,3101.0,0.037085,0.013120,0.167339,0.000000
7,MA,11.000,210.0000,666.0000,887.0,999.0000,17436.000,5008.0000,27979.0,0.031702,0.012044,0.132987,0.011011
8,MG,1.000,57.0000,182.0000,240.0,551.0000,6005.000,1443.0000,8011.0,0.029959,0.009492,0.126126,0.001815
9,PA,28.000,758.0000,1929.0000,2715.0,1375.0000,24969.000,6987.0000,33699.0,0.080566,0.030358,0.276084,0.020364
10,PE,19.000,659.0000,1790.0000,2468.0,1163.0000,22247.000,6509.0000,29919.0,0.082489,0.029622,0.275004,0.016337
11,PI,2.001,36.9978,99.0012,138.0,299.1315,3186.493,758.2241,4243.0,0.032524,0.011611,0.130570,0.006689
12,RJ,11.000,488.0000,864.0000,4361.0,350.0000,9156.000,2194.0000,40024.0,0.108960,0.053298,0.393801,0.031429
13,RO,1.000,51.0000,85.0000,137.0,219.0000,3198.000,445.0000,3862.0,0.035474,0.015947,0.191011,0.004566
14,RS,1.000,33.0000,175.0000,209.0,336.0000,5495.000,1217.0000,7048.0,0.029654,0.006005,0.143796,0.002976
15,SC,1.000,35.0000,90.0000,126.0,487.0000,5891.000,984.0000,7372.0,0.017092,0.005941,0.091463,0.002053
16,SE,8.000,40.0000,78.0000,126.0,384.0000,4921.000,606.0000,5911.0,0.021316,0.008128,0.128713,0.020833
17,TO,0.000,26.0000,42.0000,68.0,307.0000,2637.000,333.0000,3277.0,0.020751,0.009860,0.126126,0.000000
18,Brasil,112.001,3513.9978,9071.0012,15906.0,10047.1315,165635.493,42612.2241,257507.0,0.061769,0.021215,0.212873,0.011148

In [ ]:
def load_srag_lethality_rate(granularity):
    assert granularity in ["state", "country"]
    df = pd.read_csv(SRAG_PATH)
    if granularity == 'country':
        to_group = ['faixa_etaria', 'CLASSI_FIN']
    else:
        to_group = ['SG_UF_INTE', 'faixa_etaria', 'CLASSI_FIN']

    return (group_srag(df, to_group))

In [ ]:
def load_lethality_rate(granularity):
    assert granularity in ["state", "country"]
    return (pd.read_csv(LETHALITY_PATH))

In [74]:
a = pd.read_csv('lethality_rates.csv').set_index('state').rename(columns={'adult_lethality': 'Adulto',
                                                   'elder_lethality': 'Idoso',
                                                   'young_lethality': 'Jovem'})

In [72]:
a.query("state == 'AC'")

,state,deaths_young,deaths_adult,deaths_elder,deaths_total,cases_young,cases_adult,cases_elder,cases_total,total_lethality,Adulto,Idoso,Jovem
0,AC,1.0,31.0,65.0,97.0,185.0,3832.0,483.0,4500.0,0.021556,0.00809,0.134576,0.005405

In [79]:
'SP' in a.index

False

In [83]:
a.loc['AC'][['Adulto', 'Idoso', 'Jovem']]

Adulto    0.008090
Idoso     0.134576
Jovem     0.005405
Name: AC, dtype: float64

In [84]:
a.loc['Brasil']

deaths_young          112.001000
deaths_adult         3513.997800
deaths_elder         9071.001200
deaths_total        15906.000000
cases_young         10047.131500
cases_adult        165635.493000
cases_elder         42612.224100
cases_total        257507.000000
total_lethality         0.061769
Adulto                  0.021215
Idoso                   0.212873
Jovem                   0.011148
Name: Brasil, dtype: float64